In [1]:
import scipy.io
import numpy as np

In [2]:
# mat = scipy.io.loadmat('2015_BOE_Chiu/2015_BOE_Chiu/Subject_01.mat')
mat = scipy.io.loadmat('./archive_1/AMD_2/AMD_2/Farsiu_Ophthalmology_2013_AMD_Subject_1001.mat')

In [3]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Jul 09 11:47:32 2013',
 '__version__': '1.0',
 '__globals__': [],
 'images': array([[[174, 189,  67, ..., 162,  81,  91],
         [171, 195,   7, ..., 154,  96,  86],
         [168, 193,  92, ..., 156,  79,  81],
         ...,
         [157, 161,  54, ..., 153,   0, 186],
         [145, 170, 108, ..., 152,  89, 187],
         [148, 166,  81, ..., 151,  82, 189]],
 
        [[170, 203,  81, ..., 168, 136,  66],
         [164, 204,  53, ..., 175,  87,  79],
         [164, 204,  84, ..., 173,  98,  69],
         ...,
         [179, 164,  98, ..., 171,  78, 204],
         [177, 171,  77, ..., 147,  95, 203],
         [176, 171,  23, ..., 154,   0, 205]],
 
        [[162, 209, 114, ..., 166, 146,  72],
         [159, 209,  47, ..., 176, 154,  76],
         [155, 207,  68, ..., 166, 141,  86],
         ...,
         [186, 161,  82, ..., 165,  55, 204],
         [180, 165,  22, ..., 163, 126, 202],
         [180, 158,  

In [4]:
# mask = np.logical_not(np.isnan( mat['automaticLayersDME']))
mask = np.logical_not(np.isnan( mat['layerMaps']))

In [7]:
# mat['automaticLayersDME'][mask]
mat['layerMaps'][mask]

array([ 70., 146., 154., ...,  63., 147., 153.])

In [18]:
mask = np.logical_not(np.isnan( mat['manualLayers1']))
print(mat['manualLayers1'][mask].shape)
print(mat['manualLayers1'].shape)

(46294,)
(8, 768, 61)


In [19]:
mask = np.logical_not(np.isnan( mat['manualLayers2']))
print(mat['manualLayers2'][mask].shape)
print(mat['manualLayers2'].shape)

(46110,)
(8, 768, 61)


In [17]:
print(mat['images'].shape)

(496, 768, 61)


In [21]:
mat['images'][0, :, :]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [23]:
mat['images'][:, 0, :]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [ 27,  18,  18, ...,   0, 255, 255],
       [  0,  21,   0, ...,   0, 255, 255],
       [  0,  22,   0, ...,   0, 255, 255]], dtype=uint8)